### ISSUE TITLE
incomplete license description for CUDD

### ISSUE THREAD

**Issue by slivingston** [VerifiableRobotics/slugs#14]
The CUDD sources tarball includes dddmp, which is not open source (and not under the same license as CUDD). E.g., consult the text [at lines 15-24 of lib/cudd-3.0.0/dddmp/dddmp.h](https://github.com/VerifiableRobotics/slugs/blob/be6b5148f4f56391d6928649cf6f7c2372e007fb/lib/cudd-3.0.0/dddmp/dddmp.h#L15-L24). This should be clarified in [the README of slugs](https://github.com/VerifiableRobotics/slugs/blob/be6b5148f4f56391d6928649cf6f7c2372e007fb/README.md), which only mentions LICENSE "in the lib/cudd-3.0.0 folder".

**Comment by progirep** [comment]
Hi Scott. Excellent catch. Thanks a lot for pointing this out. I've added the clarification that you suggested.
