### ISSUE TITLE
request to create versions (and releases)

### ISSUE THREAD

**Issue by slivingston** [VerifiableRobotics/slugs#16]
Would you consider introducing versions as tags in this repository?

Otherwise, it is difficult to create reliable references to `slugs`. My motivating use-case is a script that fetches, builds, and runs `slugs` as part of tests for an interface that is being developed in [TuLiP](https://github.com/tulip-control/tulip-control/). Without tags, the only potentially reliable reference is commit hashes on master branch. However, to get a particular commit, it is necessary to clone the Slugs repository and checkout that particular commit. Furthermore, the clone must be of sufficient depth, which makes the solution a relatively heavy weight long-duration solution. Furthermore, it requires Git to be installed wherever the script is going to be used.

There are many other motivating use-cases for versioning. Tell me if you want more to be described here.

**Comment by progirep** [comment]
Hi @slivingston - I've just created a first tag that will hopefully suit your needs for versions/releases. Currently, the idea is to only have commits of the "master" branch versioned. So new tagged versions will not exactly be added often.

**Comment by slivingston** [comment]
@progirep Thanks! Your proposed tag style is good for me.
